name=OAM-LEDA-CAN-GW
version=0.0.1
author=sisamiwe
maintainer=sisamiwe
sentence=Gateway between Ledatronic and KNX, that can be parametrized with ETS
paragraph=
category=Application
url=*
architectures=*
includes=
